// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfoxlnxwtrdhdguexzex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmb3hsbnh3dHJkaGRndWV4emV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTAyODcsImV4cCI6MjA1Njg2NjI4N30.U5aDG2B18qcrksZUqPg7m5ovKvdUhi1dMywM1B2MuSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);